'''
Author: Matthew Mettler
Project Euler, Problem 29
https://projecteuler.net/problem=29

How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
Status: Complete, not officially submitted

Correct according to https://code.google.com/p/projecteuler-solutions/wiki/ProjectEulerSolutions
[Finished in 3.6s]
'''

print(len(set([a**b for a in range(2, 101) for b in range(2, 101)])))